<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override updated by Lightning App Builder during activation.</comment>
        <content>Account_Record_Page_Three_Column</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Account</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override updated by Lightning App Builder during activation.</comment>
        <content>Contact_Record_Page_Three_Column</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override updated by Lightning App Builder during activation.</comment>
        <content>Lead_Record_Page_Three_Column</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Lead</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override updated by Lightning App Builder during activation.</comment>
        <content>Opportunity_Record_Page_Three_Column</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Sales Console</label>
    <navType>Console</navType>
    <tabs>standard-home</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Campaign</tabs>
    <tabs>standard-Task</tabs>
    <tabs>standard-Event</tabs>
    <tabs>standard-ContentNote</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-Feed</tabs>
    <tabs>standard-CollaborationGroup</tabs>
    <tabs>standard-File</tabs>
    <tabs>Explosive_Precursor_File__c</tabs>
    <tabs>parent1__c</tabs>
    <tabs>parent2__c</tabs>
    <tabs>parent3__c</tabs>
    <tabs>parent4__c</tabs>
    <tabs>child1__c</tabs>
    <tabs>child2__c</tabs>
    <tabs>child3__c</tabs>
    <tabs>child4__c</tabs>
    <tabs>child5__c</tabs>
    <tabs>parent5__c</tabs>
    <tabs>parent6__c</tabs>
    <tabs>junctionObj__c</tabs>
    <tabs>vaultp1__c</tabs>
    <tabs>vaultc1__c</tabs>
    <tabs>vaultc2__c</tabs>
    <tabs>vaultc3__c</tabs>
    <tabs>ExternalObject__x</tabs>
    <tabs>Notification__c</tabs>
    <tabs>User_Notification__c</tabs>
    <tabs>CustomObejct1__c</tabs>
    <tabs>CustomObject2__c</tabs>
    <tabs>CustomObject3__c</tabs>
    <tabs>CustObj__c</tabs>
    <tabs>CustObj2__c</tabs>
    <tabs>CustObj3__c</tabs>
    <tabs>testorg__c</tabs>
    <tabs>dlConfig__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>LightningSalesConsole_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>CustObj2__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj3__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObejct1__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObject2__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObject3__c</tab>
        </mappings>
        <mappings>
            <tab>Explosive_Precursor_File__c</tab>
        </mappings>
        <mappings>
            <tab>ExternalObject__x</tab>
        </mappings>
        <mappings>
            <tab>Notification__c</tab>
        </mappings>
        <mappings>
            <tab>User_Notification__c</tab>
        </mappings>
        <mappings>
            <tab>child1__c</tab>
        </mappings>
        <mappings>
            <tab>child2__c</tab>
        </mappings>
        <mappings>
            <tab>child3__c</tab>
        </mappings>
        <mappings>
            <tab>child4__c</tab>
        </mappings>
        <mappings>
            <tab>child5__c</tab>
        </mappings>
        <mappings>
            <tab>dlConfig__c</tab>
        </mappings>
        <mappings>
            <tab>junctionObj__c</tab>
        </mappings>
        <mappings>
            <tab>parent1__c</tab>
        </mappings>
        <mappings>
            <tab>parent2__c</tab>
        </mappings>
        <mappings>
            <tab>parent3__c</tab>
        </mappings>
        <mappings>
            <tab>parent4__c</tab>
        </mappings>
        <mappings>
            <tab>parent5__c</tab>
        </mappings>
        <mappings>
            <tab>parent6__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-Campaign</tab>
        </mappings>
        <mappings>
            <tab>standard-CollaborationGroup</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-ContentNote</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-Event</tab>
        </mappings>
        <mappings>
            <tab>standard-Feed</tab>
        </mappings>
        <mappings>
            <tab>standard-File</tab>
        </mappings>
        <mappings>
            <tab>standard-Lead</tab>
        </mappings>
        <mappings>
            <tab>standard-Opportunity</tab>
        </mappings>
        <mappings>
            <tab>standard-Task</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
        <mappings>
            <tab>testorg__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc1__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc2__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc3__c</tab>
        </mappings>
        <mappings>
            <tab>vaultp1__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
